CREATE TABLE URL (
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	ALIAS VARCHAR(10) NOT NULL UNIQUE,
	URL_SHORT VARCHAR(30) NOT NULL,
	URL_FULL VARCHAR(100) NOT NULL UNIQUE,
	TEMPO VARCHAR(20)
)ENGINE = InnoDB DEFAULT CHARSET=utf8;